# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50d59eca6fd0bf520c71832449c6d536bb7c3d6d7367999493d11a616413b48c456a99c6125e0b7710fd0e52e3e90afcabd73764397476305342d59f9759567a

test:
  secret_key_base: 55349051acc3257447db8251242b4b8eaac8d076d20d2b7d415df1e1d9d8acfb4789456d93ba569366e5958c35286b91a5041c4a6f4b19ff172de05a6fe2772d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
